### ISSUE TITLE
Create SQL database

### ISSUE THREAD

**Issue by Fuenfgeld** [Fuenfgeld/DMA2024TeamA#1]

**Comment by JEWeixler** [comment]
Link zu den Tabellen und Datentypen:
https://github.com/synthetichealth/synthea/wiki/CSV-File-Data-Dictionary

**Comment by AlissiaK** [comment]
<img width="1040" alt="SQL-database" src="https://github.com/Fuenfgeld/DMA2024TeamA/assets/156526890/bf6601a3-7278-404e-a246-d5be412aba8a">

Klappt in SQLite jetzt auch mit Daten. Die Punkte in der Bevölkerungszahl werden allerdings als Komma erkannt. 
[County.csv](https://github.com/Fuenfgeld/DMA2024TeamA/files/13998190/County.csv) <- Hier nochmal die Datei ohne Punkte, dann geht es
