### ISSUE TITLE
Forschungsfrage überarbeiten

### ISSUE THREAD

**Issue by Uti404** [Fuenfgeld/DMA2024TeamA#10]

**Comment by AlissiaK** [comment]
Wie ist ein schwerer Covid-Verlauf definiert?

**Comment by AlissiaK** [comment]
Wie hängt die Bevölkerungsdichte/Wohnort mit dem Covid-Verlauf zusammen?

**Comment by AlissiaK** [comment]
Welchen Einfluss hat das Patientenalter auf den Covid-Verlauf?

**Comment by CV293008** [comment]
Ist die Wahrscheinlichkeit schwer an Covid zu erkranken abhängig von der Bevölkerungsdichte/ Wohnort

**Comment by CV293008** [comment]
Welcher Zusammenhang besteht zwischen Wohnort und Beatmung während der Covid-Erkrankung?

**Comment by Uti404** [comment]
Auf folgende Forschungsfrage wurde sich geeinigt:
Wie hängt die Bevölkerungsdichte mit dem Covid-Verlauf zusammen?
Welcher Zusammenhang besteht zwischen Wohnort und Beatmung während der Covid-Erkrankung?

Desweitern muss noch geklärt werden, wie ein schwerer Covid-Verlauf definiert ist.
