### ISSUE TITLE
Nötige Datentabellen heraussuchen

### ISSUE THREAD

**Issue by Uti404** [Fuenfgeld/DMA2024TeamA#12]

**Comment by Uti404** [comment]
Careplans
-> gibt den Start und Stop der Covid-19 Infektion an
-> REASONDESCRIPTION gibt an, ob **COVID-19** oder **Suspected COVID-19**, hier evtl. herausfiltern

Conditions
-> Gibt die Symptome an

Devices
-> Start/Stop mit Start/Stop der Erkrankung vergleichen und herausfiltern

Disease ->leer

Encounters
-> ENCOUNTERCLASS gibt an ob wellness oder ambulatory,...

Immunizations
-> hier wurden Impfungen aufgeführt, allerdings ohne Corona Impfung, somit eher unnötig?

Medications
-> eher nicht wichtig oder?

Observations
-> einige Laborwerte wurden hier mit aufgeführt, wichtig für den Schwergrad des Verlaufs

Patients
-> Geburtstag, sowie Todestag wichtig (Tote herausfiltern)
-> GENDER und RACE 
-> **Geburtsort** und County

Procedures
-> bei DESCRIPTION wird aufgeführt ob Sauerstoff verabreicht wurde

Supplies
-> evtl. DESCRIPTION mit nutzen

**Comment by JEWeixler** [comment]
Danke
Wenn wir das als 'Star scheme' aufsetzen wollen, sollten wir uns darüber unterhalten, was die zntrale Faktentabelle ist.
ToDo für unser Meeting

**Comment by CV293008** [comment]
[Abfragen SQL.xlsx](https://github.com/Fuenfgeld/DMA2024TeamA/files/14069290/Abfragen.SQL.xlsx)

**Comment by CV293008** [comment]
habe mal einige Abfragen kombiniert und start stop der conditions genommen

**Comment by AlissiaK** [comment]
Datentabellen selektiert --> Sternschema ist "Folge-Issue" #14
