### ISSUE TITLE
Sternschema

### ISSUE THREAD

**Issue by AlissiaK** [Fuenfgeld/DMA2024TeamA#14]
Due Date: 2024-01-27 --> Meeting am Samstag

**Comment by AlissiaK** [comment]
![IMG_B5CB1BEC829A-1](https://github.com/Fuenfgeld/DMA2024TeamA/assets/156526890/73a5cd82-32fa-4376-9905-60c1382024f2)

**Comment by Uti404** [comment]
``` mermaid
---
title: Sternschema
---
   erDiagram
Wohnort ||--|{ seaside : contains
Wohnort ||--o{ population_density : contains
Patient ||--o{ Wohnort : contains
Patient ||--|{ Schweregrad : contains
Schweregrad ||--o{ Laborwerte : contains
Schweregrad ||--|{ Beatmung : contains
Schweregrad ||--o{ Sauerstoff : contains
Schweregrad ||--|{ Death : contains
Schweregrad ||--o{ Symptome : contains
```

**Comment by Uti404** [comment]
Hier ein Versuch das ganze mit mermaid zu machen, aber das finde ich eher schwierig, da hier die Pfeile beschriftet werden müssen.

**Comment by Uti404** [comment]
Der folgende Link führt zu Mindmeister, hier hab ich sozusagen mit einer MindMap versucht.
https://mm.tt/app/map/3136990599?t=3aaoIAxMhl

**Comment by AlissiaK** [comment]
![IMG_0015](https://github.com/Fuenfgeld/DMA2024TeamA/assets/156526890/14b2b1b5-4897-4f5e-b831-2072712170d4)

**Comment by AlissiaK** [comment]
<img width="732" alt="Bildschirmfoto 2024-01-29 um 22 12 53" src="https://github.com/Fuenfgeld/DMA2024TeamA/assets/156526890/7a054cfe-5934-4e5e-84d8-237f869e77fa">

Vielleicht zur Übersicht ganz hilfreich. Damit Ihr bei Änderungswünschen nicht alles neu tippen müsst, ist anbei der Code für https://dbdiagram.io/d 

In den Notizen für den SEVIT Score habe ich die nötigen spalten aus den Tabellen ergänzt. Wahrscheinlich ist es besser mit Codes zu arbeiten als mit descriptions


Table County {
  county string
  population integer
  density integer 
  seaside bool
}

Table patients {
  id integer [primary key]
  Gender string
  Income integer
  Age integer
  BirthPlace string
  Race string
  county string


}

Table MAPCOV {
  county integer
  population integer
  density integer 
  seaside bool
  
  id integer [primary key]
  Gender string
  Income integer
  Age integer
  BirthPlace string
  Race string


Start date
  Stop date
  duration days 

Beatmung bool [note: 'Devices.description/code']
  Sauerstoff bool [note: 'procedures.description/code']
  Death bool [note: 'patients.DeathDate']
  Medications bool [note: 'medications.code']
  Symptome string [note: 'conditions.code']
  Laborwerte string [note: 'observations.code']
  Encounter string [note: 'Encounter.EncounterClass']

}

Table SEVITScore {
  Beatmung bool [note: 'Devices.description/code']
  Sauerstoff bool [note: 'procedures.description/code']
  Death bool [note: 'patients.DeathDate']
  Medications bool [note: 'medications.code']
  Symptome string [note: 'conditions.code']
  Laborwerte string [note: 'observations.code']
  Encounter string [note: 'Encounter.EncounterClass']
}

Table Covid {
  Start date
  Stop date
  duration days 

} 

Ref: SEVITScore.Beatmung > MAPCOV.Beatmung 
Ref: SEVITScore.Sauerstoff > MAPCOV.Sauerstoff
Ref: SEVITScore.Death > MAPCOV.Death
Ref: SEVITScore.Medications > MAPCOV.Medications
Ref: SEVITScore.Symptome > MAPCOV.Symptome
Ref: SEVITScore.Laborwerte > MAPCOV.Laborwerte
Ref: SEVITScore.Encounter > MAPCOV.Encounter

Ref: County.county > MAPCOV.county
Ref: County.population > MAPCOV.population
Ref: County.density > MAPCOV.density
Ref: County.seaside > MAPCOV.seaside

Ref: patients.id > MAPCOV.id
Ref: patients.Gender > MAPCOV.Gender
Ref: patients.Income > MAPCOV.Income
Ref: patients.Age > MAPCOV.Age
Ref: patients.BirthPlace > MAPCOV.BirthPlace
Ref: patients.Race > MAPCOV.Race
Ref: patients.county > MAPCOV.county

Ref: Covid.Start > MAPCOV.Start
Ref: Covid.Stop > MAPCOV.Stop
Ref: Covid.duration > MAPCOV.duration

**Comment by Uti404** [comment]
[Kopie Sternschema MAPCOV.pdf](https://github.com/Fuenfgeld/DMA2024TeamA/files/14129733/Kopie.Sternschema.MAPCOV.pdf)

Hier mal ein Versuch von mir, hier gibts noch verschiedene Design, die man anwenden könnte. Gerne können wir das ja am Samstag einmal zusammen anschauen.

**Comment by Uti404** [comment]
[Kopie Sternschema MAPCOV (1).pdf](https://github.com/Fuenfgeld/DMA2024TeamA/files/14150731/Kopie.Sternschema.MAPCOV.1.pdf)

**Comment by Uti404** [comment]
[Kopie Sternschema MAPCOV (2).pdf](https://github.com/Fuenfgeld/DMA2024TeamA/files/14156371/Kopie.Sternschema.MAPCOV.2.pdf)

**Comment by JEWeixler** [comment]
Factsheet in der Mitte derzeit:  
Id | patients_INFO_Id
BIRTHDATE | patients_INFO_BIRTHDATE
DEATHDATE | patients_INFO_DEATHDATE
GENDER | patients_INFO_GENDER
COUNTY | patients_INFO_COUNTY
LAT | patients_INFO_LAT
LON | patients_INFO_LON
DENSITY_per_sqm | county_info_DENSITY_per_sqm
SEASIDE | county_info_SEASIDE
stdt_covid | conditions_INFO_START (Filter: 'COVID19')
endt_covid | conditions_INFO_STOP (Filter: 'COVID19')
AGE_Covid | Neu: Berechnet aus BIRTHDATE und stdt_covid
Ventilation | procedures_INFO_DESCRIPTION (Filter nach 'Mechanical ventilator (physical object)'; Gruppiert nach 'Patient')
Medications | medications_info_REASONDESCRIPTION (Filter nach 'COVID-19'; Gruppiert nach 'Patient')
inpatient | encounters_info_ENCOUNTERCLASS (Filter nach 'inpatient'; Gruppiert nach 'Patient')
Disorder | conditions_INFO_DESCRIPTION (Filter nach 'Disorder'; Gruppiert nach 'Patient')
Death | Neu: Grundlage DEATHDATE.
SEVID | Neu: Grundlage Ventilation,  Medications, inpatient, Disorder, Death
