### ISSUE TITLE
Projektnamen festlegen

### ISSUE THREAD

**Issue by AlissiaK** [Fuenfgeld/DMA2024TeamA#15]
Die meisten Projekte haben "fancy" Namen. Mein Brainstorming hat ergeben: 

**CovRes** (Covid + Residence) Connection between Covid and residence of the Patient
Massachusetts Study of Population density and Covid-19 severity **(MAP-Cov) oder MAP-Cov SD**

_Vorschlag von ChatGPT:_ 
Massachusetts Pandemic Analysis Project **(MAPAP)**
EpiDense MA: Population Density and COVID Severity
Urban Resilience: A Massachusetts COVID Investigation

**Comment by Uti404** [comment]
Metting am 27.01.2024
Entschlossen den folgenden Namen zu nutzten.
**MAP-COV** - Massachusetts Study of Population density and Covid-19 severity
