### ISSUE TITLE
Score-Schema für einen schweren COVID-19 Verlauf

### ISSUE THREAD

**Issue by CV293008** [Fuenfgeld/DMA2024TeamA#16]

**Comment by Uti404** [comment]
1. Gestorben (Patients)
2. Beatmung (Devices)
3. Sauerstoff Zugabe (Procedures)
4. Symptome (Conditions)
5. Wellness/Ambulatory (Encounters)
6. Laborwerte (Observations)
7. Kosten der Behandlung
8. Gegeben Medikamente (Medications)

**Comment by JEWeixler** [comment]
Bei den Conditions müssen wir raussuchen, welche für einen schweren Verlauf stehen.   
In der Liste würde ich alles mit (disorder) vorschlagen.

**Comment by CV293008** [comment]
Laborwerte:
Temperatur: >38,0°C
O2 arteriell 95-99% alles < 95% + Respirationsrate > 20/min --> zu wenig Sauerstoff, erhöhte Atmung
Fibrin D-Dimer > 0,5 --> Hinweis auf eine Thrombose/ Infarkt
Puls >80 /min
Hinweis: bei den harmlosen Covic-Verläufen gibt es kaum Laborwerte, Laborwerte wurden erst bei den schwereren Verläufen erhoben. Da helfen die Parameter weniger, es sind Entzündungsparameter, die erhöht sind

vielleicht kann man noch Vorerkrankungen wie Diabetes Herzinfarkt

**Comment by Uti404** [comment]
Kann man dann nicht so einen schweren Covid-Verlauf angeben?

Wurden Laborwerte erfasst? Ja/Nein

**Comment by CV293008** [comment]
im Prinzip ja, wobei nicht alle Patienten mit einem schweren Verlauf gestorben sind

**Comment by CV293008** [comment]
Conditions: bei einem Patienten mehrere Descriptions
Dyspnea, Wheezing, loss of taste, (cough), Hypoxemia, respiratory distress

**Comment by Uti404** [comment]
Ventilation, Medications, inpatient, Disorder, Death
