### ISSUE TITLE
Datencleaning beschreiben, Übertragen in DMP

### ISSUE THREAD

**Issue by JEWeixler** [Fuenfgeld/DMA2024TeamA#18]
zum Beispiel:
Pro Tabelle: Welche Filter sollten verwendet werden?

**Comment by AlissiaK** [comment]
Todesdaten vor Dezember 2019
SELECT patients.id, patients.deathdate
FROM patients
where deathdate is not NULL and deathdate < '2019-12-01'

**Comment by JEWeixler** [comment]
Patiententabelle:
Gesamten Eintrag zum Patienten löschen, wenn das Todesdatum vor 2019 liegt

**Comment by Uti404** [comment]
Devicestabelle:
Beatmungen, welche vor der Covid Erkrankung erfolgten herauslöschen.

**Comment by CV293008** [comment]
Careplans: alle Daten vor 2020 bei Start, Stop herauslöschen

**Comment by CV293008** [comment]
Tabelle Medications: base_cost, total costs, payer, payer_coverage, dispenses löschen
imaging_studies, disease komplett löschen, da keine Daten
conditiones, devices: alle Daten vor 2020 löschen

**Comment by JEWeixler** [comment]
Siehe Qry_cond_covid.ipynb  
(https://github.com/Fuenfgeld/DMA2024TeamA/blob/60baccf0e3a398064987bd4fb1966b7d9715c4be/Qry_cond_covid.ipynb)  
Abfrage, die Datumsfelder danach filtert, ob etwas parallel zu COVID auftrat. Kann als Tempalte für weiteres Cleaning verwendet werden. Erweiterbar um weitere Prüfungen, z.B. Datum muss nach 2020 sein.

**Comment by JEWeixler** [comment]
Übergeben an Issue #21
