### ISSUE TITLE
Analysen entwicklen

### ISSUE THREAD

**Issue by JEWeixler** [Fuenfgeld/DMA2024TeamA#23]
Welche Analysen sind sinnvoll?

**Comment by Uti404** [comment]
Geomapping

**Comment by AlissiaK** [comment]
Für Geomapping musste "LAT", "LON" (Längen- und Breitengrade)mit ins das Factsheet übernommen werden. Dadurch andere Ergebnisse in Heatmap?

**Comment by JEWeixler** [comment]
Für die relevanten Fragestellungen und Korrelationen kann ein chi-quadrat durchgeführt werden. Der p-Wert zeigt eine oder keinen signifikanten Zusammenhang an.
