### ISSUE TITLE
Link funktioniert nicht

### ISSUE THREAD

**Issue by Fuenfgeld** [Fuenfgeld/DMA2024TeamA#28]
![image](https://github.com/Fuenfgeld/DMA2024TeamA/assets/32547123/e62d35f4-74b4-42fc-8a6f-0a5721488fc6)

**Comment by Fuenfgeld** [comment]
Im readme und im wiki

**Comment by Fuenfgeld** [comment]
![image](https://github.com/Fuenfgeld/DMA2024TeamA/assets/32547123/cab4e287-c0b0-42cf-bf36-61d88dd1698b)

**Comment by AlissiaK** [comment]
fixed

**Comment by Fuenfgeld** [comment]
Schaut euch auch Sicherheitshalber die anderen Links an.

**Comment by Uti404** [comment]
Im Wiki wurden alle links geprüft

**Comment by Uti404** [comment]
Alle Links wurden noch einmal überprüft und ggf. korrigiert.
