### ISSUE TITLE
Misleading description of the data dictionary (where is the file description)

### ISSUE THREAD

**Issue by Fuenfgeld** [Fuenfgeld/DMA2024TeamA#29]
![image](https://github.com/Fuenfgeld/DMA2024TeamA/assets/32547123/bb048f90-092d-4504-aab3-a953013d1a8a)

**Comment by Fuenfgeld** [comment]
Die file Struktur fehlt

**Comment by AlissiaK** [comment]
@Uti404 Die Filestruktur des Projekts steht momentan mit im Sternschema (Links im Footer habe ich angepasst). Sollte vielleicht besser eine eigene Seit im Wiki bekommen, oder?
