### ISSUE TITLE
Datenmanagementplan anlegen

### ISSUE THREAD

**Issue by AlissiaK** [Fuenfgeld/DMA2024TeamA#3]
https://docs.google.com/document/d/1_2GnUqEe7J8sZzjgDwd0qkzBPecG28pbP11VbhVDwq0/edit?usp=sharing
Kopie des Dokuments erstellt, begonnen für unser Projekt zu "personalisieren" und mit euch als Mitbearbeiter geteilt!

**Comment by Uti404** [comment]
https://docs.google.com/document/d/1Oyos_QTr3Sa6YDPQ4w0kDeofFXpA5AB0exQVLMGJgcw/edit?usp=sharing
(Link zum Template von Maximilian Fünfgeld/Tobias Schmidt)

**Comment by AlissiaK** [comment]
DMP angelegt. Bearbeitung ongoing.
