### ISSUE TITLE
Colabbook nicht ohne fehler ausführbar

### ISSUE THREAD

**Issue by Fuenfgeld** [Fuenfgeld/DMA2024TeamA#31]
![image](https://github.com/Fuenfgeld/DMA2024TeamA/assets/32547123/fd194638-8a99-42a9-af42-2cbcac8a4e00)

**Comment by Fuenfgeld** [comment]
Schaut euch an wie ihr zugang zu eueren daten geben wollt

**Comment by JEWeixler** [comment]
Abschnitt "Publikation, Verfügbarmachung der Daten" im Datenmanagementplan dahingehend erweitert.
