### ISSUE TITLE
Archivierung

### ISSUE THREAD

**Issue by Fuenfgeld** [Fuenfgeld/DMA2024TeamA#32]
![image](https://github.com/Fuenfgeld/DMA2024TeamA/assets/32547123/68e9810e-b031-49b9-aa0a-6a9299d15d96)

**Comment by Fuenfgeld** [comment]
Hier feht noch welche Artefakte ihr aufbewahern wollt. (welche datensätze, Welche Dokumentation etc.)

**Comment by AlissiaK** [comment]
![image](https://github.com/Fuenfgeld/DMA2024TeamA/assets/156526890/30daaf48-723e-4339-b47c-fa63774258d6)
