### ISSUE TITLE
Countydaten zusammenstellen

### ISSUE THREAD

**Issue by AlissiaK** [Fuenfgeld/DMA2024TeamA#4]

**Comment by Uti404** [comment]
Habe jetzt mal die Population, die Fläche der Countys und die Dichte der Bevölkerung angegeben. 
Alle Daten hab ich aus folgender Interetseite: https://worldpopulationreview.com/states/massachusetts/counties
[Population Massachusetts - Tabellenblatt1.csv](https://github.com/Fuenfgeld/DMA2024TeamA/files/13942252/Population.Massachusetts.-.Tabellenblatt1.csv)
